In [3]:
import pandas as pd

df = pd.read_csv('Dataset.csv')

In [ ]:
df.head()

,show_id,type,title,director,country,date_added,release_year,rating,duration,listed_in
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,United States,9/25/2021,2020,PG-13,90 min,Documentaries
1,s3,TV Show,Ganglands,Julien Leclercq,France,9/24/2021,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act..."
2,s6,TV Show,Midnight Mass,Mike Flanagan,United States,9/24/2021,2021,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries"
3,s14,Movie,Confessions of an Invisible Girl,Bruno Garotti,Brazil,9/22/2021,2021,TV-PG,91 min,"Children & Family Movies, Comedies"
4,s8,Movie,Sankofa,Haile Gerima,United States,9/24/2021,1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies"

In [4]:
# Check missing values in each column
df.isnull().sum()

show_id         0
type            0
title           0
director        0
country         0
date_added      0
release_year    0
rating          0
duration        0
listed_in       0
dtype: int64

In [ ]:
# Check missing values as a percentage
(df.isnull().sum() / len(df)) * 100

show_id         0.0
type            0.0
title           0.0
director        0.0
country         0.0
date_added      0.0
release_year    0.0
rating          0.0
duration        0.0
listed_in       0.0
dtype: float64

In [ ]:
# Check for fully duplicate rows
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8790 entries, 0 to 8789
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8790 non-null   object
 1   type          8790 non-null   object
 2   title         8790 non-null   object
 3   director      8790 non-null   object
 4   country       8790 non-null   object
 5   date_added    8790 non-null   object
 6   release_year  8790 non-null   int64
 7   rating        8790 non-null   object
 8   duration      8790 non-null   object
 9   listed_in     8790 non-null   object
dtypes: int64(1), object(9)
memory usage: 686.8+ KB

In [ ]:
df['director'].value_counts().head(10)

director
Not Given                 2588
Rajiv Chilaka               20
Alastair Fothergill         18
Raúl Campos, Jan Suter      18
Marcus Raboy                16
Suhas Kadav                 16
Jay Karas                   14
Cathy Garcia-Molina         13
Jay Chapman                 12
Martin Scorsese             12
Name: count, dtype: int64

In [ ]:
df['country'].value_counts().head(10)

country
United States     3240
India             1057
United Kingdom     638
Pakistan           421
Not Given          287
Canada             271
Japan              259
South Korea        214
France             213
Spain              182
Name: count, dtype: int64

In [ ]:
df['country'].unique()[:20]

array(['United States', 'France', 'Brazil', 'United Kingdom', 'India',
       'Germany', 'Pakistan', 'Not Given', 'China', 'South Africa',
       'Japan', 'Nigeria', 'Spain', 'Philippines', 'Australia',
       'Argentina', 'Canada', 'Hong Kong', 'Italy', 'New Zealand'],
      dtype=object)

In [ ]:
df['date_added'].value_counts().head(10)

date_added
1/1/2020      110
11/1/2019      91
3/1/2018       75
12/31/2019     74
10/1/2018      71
10/1/2019      62
11/1/2018      60
7/1/2021       60
9/1/2021       56
1/1/2018       55
Name: count, dtype: int64

In [ ]:
df['duration'].value_counts().head(10)

duration
1 Season     1791
2 Seasons     421
3 Seasons     198
90 min        152
94 min        146
97 min        146
93 min        146
91 min        144
95 min        137
96 min        130
Name: count, dtype: int64

In [ ]:
df['rating'].value_counts()

rating
TV-MA       3205
TV-14       2157
TV-PG        861
R            799
PG-13        490
TV-Y7        333
TV-Y         306
PG           287
TV-G         220
NR            79
G             41
TV-Y7-FV       6
NC-17          3
UR             3
Name: count, dtype: int64

In [5]:
print("Duplicate show_id:", df['show_id'].duplicated().sum())
print("Duplicate title+type:", df.duplicated(subset=['title', 'type']).sum())

Duplicate show_id: 0
Duplicate title+type: 3

In [6]:
print("Director 'Not Given':", (df['director'] == 'Not Given').sum())
print("Country 'Not Given':", (df['country'] == 'Not Given').sum())

Director 'Not Given': 2588
Country 'Not Given': 287

In [7]:
dupes = df[df.duplicated(subset=['title', 'type'], keep=False)].sort_values('title')
dupes

,show_id,type,title,director,country,date_added,release_year,rating,duration,listed_in
2925,s3963,Movie,15-Aug,Swapnaneel Jayakar,India,3/29/2019,2019,TV-14,124 min,"Comedies, Dramas, Independent Movies"
4261,s5967,Movie,15-Aug,Swapnaneel Jayakar,India,3/29/2019,2019,TV-14,124 min,"Comedies, Dramas, Independent Movies"
3285,s4523,Movie,22-Jul,Paul Greengrass,Norway,10/10/2018,2018,R,144 min,"Dramas, Thrillers"
4260,s5966,Movie,22-Jul,Paul Greengrass,Norway,10/10/2018,2018,R,144 min,"Dramas, Thrillers"
393,s3997,TV Show,9-Feb,Not Given,Pakistan,3/20/2019,2018,TV-14,1 Season,"International TV Shows, TV Dramas"
537,s5965,TV Show,9-Feb,Not Given,Pakistan,3/20/2019,2018,TV-14,1 Season,"International TV Shows, TV Dramas"

In [8]:
print("Shape before:", df.shape)
df = df.drop_duplicates(subset=['title', 'type', 'release_year', 'director'], keep='first')
print("Shape after:", df.shape)
print("Duplicate title+type:", df.duplicated(subset=['title', 'type']).sum())

Shape before: (8790, 10)
Shape after: (8787, 10)
Duplicate title+type: 0

In [9]:
#Step 3: Handle null values and inconsistent formats

import numpy as np
for col in df.select_dtypes(include='object').columns:
    df[col] = df[col].str.strip()

In [10]:
df = df.replace('Not Given', np.nan)
df.isnull().sum()

show_id            0
type               0
title              0
director        2587
country          287
date_added         0
release_year       0
rating             0
duration           0
listed_in          0
dtype: int64

In [11]:
df['director'] = df['director'].fillna('Unknown')
df['country'] = df['country'].fillna('Unknown')
df.isnull().sum()

show_id         0
type            0
title           0
director        0
country         0
date_added      0
release_year    0
rating          0
duration        0
listed_in       0
dtype: int64

In [12]:
df['rating'] = df['rating'].replace({'NR': 'Not Rated', 'UR': 'Not Rated'})
df['rating'].value_counts()

rating
TV-MA        3205
TV-14        2155
TV-PG         861
R             798
PG-13         490
TV-Y7         333
TV-Y          306
PG            287
TV-G          220
Not Rated      82
G              41
TV-Y7-FV        6
NC-17           3
Name: count, dtype: int64

In [13]:
print(df.isnull().sum().sum(), "nulls left")
print("Director Unknown:", (df['director'] == 'Unknown').sum())
print("Country Unknown:", (df['country'] == 'Unknown').sum())
print("'Not Given' left:", (df == 'Not Given').sum().sum())

0 nulls left
Director Unknown: 2587
Country Unknown: 287
'Not Given' left: 0

In [14]:
# Step 4: Transform categorical and date-related columns

df['date_added'] = pd.to_datetime(df['date_added'], format='%m/%d/%Y')
df['year_added'] = df['date_added'].dt.year
df['month_added'] = df['date_added'].dt.month
df['month_name'] = df['date_added'].dt.month_name()
df['day_of_week'] = df['date_added'].dt.day_name()
df[['date_added', 'year_added', 'month_added', 'month_name', 'day_of_week']].head()

  date_added  year_added  month_added month_name day_of_week
0 2021-09-25        2021            9  September    Saturday
1 2021-09-24        2021            9  September      Friday
2 2021-09-24        2021            9  September      Friday
3 2021-09-22        2021            9  September   Wednesday
4 2021-09-24        2021            9  September      Friday

In [15]:
df['duration_value'] = df['duration'].str.extract(r'(\d+)').astype(int)
df['duration_unit'] = df['duration'].str.extract(r'([A-Za-z]+)')
df['duration_unit'] = df['duration_unit'].replace({'Seasons': 'Season'})
df[['duration', 'duration_value', 'duration_unit']].head()
df['duration_unit'].value_counts()

duration_unit
min       6124
Season    2663
Name: count, dtype: int64

In [16]:
df[['duration', 'duration_value', 'duration_unit']].head()

   duration  duration_value duration_unit
0    90 min              90           min
1  1 Season               1        Season
2  1 Season               1        Season
3    91 min              91           min
4   125 min             125           min

In [17]:
df['primary_country'] = df['country'].str.split(',').str[0].str.strip()
df['primary_genre'] = df['listed_in'].str.split(',').str[0].str.strip()
df[['country', 'primary_country', 'listed_in', 'primary_genre']].head()

,country,primary_country,listed_in,primary_genre
0,United States,United States,Documentaries,Documentaries
1,France,France,"Crime TV Shows, International TV Shows, TV Act...",Crime TV Shows
2,United States,United States,"TV Dramas, TV Horror, TV Mysteries",TV Dramas
3,Brazil,Brazil,"Children & Family Movies, Comedies",Children & Family Movies
4,United States,United States,"Dramas, Independent Movies, International Movies",Dramas

In [18]:
rating_map = {
    'TV-Y': 'Kids', 'TV-Y7': 'Kids', 'TV-Y7-FV': 'Kids', 'TV-G': 'Kids', 'G': 'Kids',
    'TV-PG': 'Older Kids', 'PG': 'Older Kids',
    'TV-14': 'Teens', 'PG-13': 'Teens',
    'TV-MA': 'Adults', 'R': 'Adults', 'NC-17': 'Adults',
    'Not Rated': 'Not Rated'
}
df['audience'] = df['rating'].map(rating_map)
print("Unmapped ratings:", df['audience'].isnull().sum())
df['audience'].value_counts()

Unmapped ratings: 0

audience
Adults        4006
Teens         2645
Older Kids    1148
Kids           906
Not Rated       82
Name: count, dtype: int64

In [19]:
for col in ['type', 'rating', 'duration_unit', 'audience']:
    df[col] = df[col].astype('category')
df.dtypes

show_id                    object
type                     category
title                      object
director                   object
country                    object
date_added         datetime64[ns]
release_year                int64
rating                   category
duration                   object
listed_in                  object
year_added                  int32
month_added                 int32
month_name                 object
day_of_week                object
duration_value              int64
duration_unit            category
primary_country            object
primary_genre              object
audience                 category
dtype: object

In [20]:
# Step 5: Create the clean dataset

df.info()
print(df.isnull().sum().sum(), "missing values left")
print("Duplicates:", df.duplicated().sum())
print("Duplicate show_id:", df['show_id'].duplicated().sum())
print("Final shape:", df.shape)

<class 'pandas.core.frame.DataFrame'>
Index: 8787 entries, 0 to 8789
Data columns (total 19 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   show_id          8787 non-null   object
 1   type             8787 non-null   category
 2   title            8787 non-null   object
 3   director         8787 non-null   object
 4   country          8787 non-null   object
 5   date_added       8787 non-null   datetime64[ns]
 6   release_year     8787 non-null   int64
 7   rating           8787 non-null   category
 8   duration         8787 non-null   object
 9   listed_in        8787 non-null   object
 10  year_added       8787 non-null   int32
 11  month_added      8787 non-null   int32
 12  month_name       8787 non-null   object
 13  day_of_week      8787 non-null   object
 14  duration_value   8787 non-null   int64
 15  duration_unit    8787 non-null   category
 16  primary_country  8787 non-null   object
 17  primary_genre    8787 non-null   object
 18  audience         8787 non-null   category
dtypes: category(4), datetime64[ns](1), int32(2), int64(2), object(10)
memory usage: 1.0+ MB
0 missing values left
Duplicates: 0
Duplicate show_id: 0
Final shape: (8787, 19)

In [21]:
df.head()

,show_id,type,title,director,country,date_added,release_year,rating,duration,listed_in,year_added,month_added,month_name,day_of_week,duration_value,duration_unit,primary_country,primary_genre,audience
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,United States,2021-09-25,2020,PG-13,90 min,Documentaries,2021,9,September,Saturday,90,min,United States,Documentaries,Teens
1,s3,TV Show,Ganglands,Julien Leclercq,France,2021-09-24,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",2021,9,September,Friday,1,Season,France,Crime TV Shows,Adults
2,s6,TV Show,Midnight Mass,Mike Flanagan,United States,2021-09-24,2021,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries",2021,9,September,Friday,1,Season,United States,TV Dramas,Adults
3,s14,Movie,Confessions of an Invisible Girl,Bruno Garotti,Brazil,2021-09-22,2021,TV-PG,91 min,"Children & Family Movies, Comedies",2021,9,September,Wednesday,91,min,Brazil,Children & Family Movies,Older Kids
4,s8,Movie,Sankofa,Haile Gerima,United States,2021-09-24,1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies",2021,9,September,Friday,125,min,United States,Dramas,Adults

In [22]:
df.to_csv('Netflix_Cleaned.csv', index=False)